### ISSUE TITLE
pyplayready.exceptions.InvalidLicense: No ECC public key in license

### ISSUE THREAD

**Issue by MrDpy** [ready-dl/pyplayready#16]
Hi,

When I execute the readme sample code, I get this error
python3 sample.py
```
Traceback (most recent call last):
  File "/opt/playready/pyplayready/cdm.py", line 242, in parse_license
    if not self._verify_encryption_key(session, parsed_licence):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/playready/pyplayready/cdm.py", line 223, in _verify_encryption_key
    raise InvalidLicense("No ECC public key in license")
pyplayready.exceptions.InvalidLicense: No ECC public key in license

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/playready/sample.py", line 37, in <module>
    cdm.parse_license(session_id, response.text)
  File "/opt/playready/pyplayready/cdm.py", line 262, in parse_license
    raise InvalidLicense(e)
pyplayready.exceptions.InvalidLicense: No ECC public key in license
```

when I execute the test for a device.prd, there is no error
pyplayready test devices/test/samsung_sph-l-na-spr_sph-l_sl.prd
```
INFO:root:pyplayready version 0.3.5 Copyright (c) 2024-2024 DevLARLEY, Erevoc, DevataDev
INFO:root:https://github.com/ready-dl/pyplayready
INFO:root:Run 'pyplayready --help' for help
INFO:license:Loaded Device: samsung_sph-l-na-spr_sph-l_sl
INFO:license:Loaded CDM
INFO:license:Opened Session
INFO:license:Created License Request (Challenge)
INFO:license:Got License Message
INFO:license:License Parsed Successfully
INFO:license:6f651ae1dbe44434bcb4690d1564c41c:88da852ae4fa2e1e36aeb2d5c94997b1
INFO:license:Clossed Session
```
The files come from the latest commit (e5782f5)
My Python version: 3.11.10

can you help me?

MrDpy

**Comment by DevLARLEY** [comment]
are you sure you're on the latest version? you seem to be using `v0.3.5`

**Comment by MrDpy** [comment]
I'm confused, I was sure I had updated the files
works perfectly
